services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      CLUSTER_ID: "gTBb85_WRXu6oQgq-brTQw"
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${HOST_IP}:9092,INTERNAL://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "requests:1:1,telemetry:1:1,commands:1:1"
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  central:
    build:
      context: .. 
      dockerfile: Deploy/Dockerfile.central 
    hostname: central
    container_name: central
    depends_on:
      init-kafka: { condition: service_completed_successfully }
    volumes:
      - ../Central:/app 
    environment:
      - REGISTRY_JWT_SECRET=dev_registry_secret
    ports: 
      - "5050:5050"
      - "8000:8000"
    command: ["python", "EV_Central.py", "5050", "broker:9092"]

  ev_cp_e:
    build:
      context: ..
      dockerfile: Deploy/Dockerfile.cps
    image: ev_cp_e:latest
    hostname: ev_cp_e_001
    container_name: ev_cp_e_001
    depends_on:
      init-kafka: { condition: service_completed_successfully }

    environment:
      - KAFKA_BOOTSTRAP=broker:9092
      - CP_ID=CP007
      - ENGINE_PORT=7000
    volumes:
      - ../ChargingPoints:/app 
    ports: 
      - "7000-7009:7000-7009"
    command: ["sleep", "infinity"]

  ev_cp_m:
    image: ev_cp_e:latest
    pull_policy: never
    hostname: ev_cp_m_001
    container_name: ev_cp_m_001
    depends_on:
      init-kafka: { condition: service_completed_successfully }
      central: { condition: service_started }
      ev_cp_e: { condition: service_started }
    environment:
      - CENTRAL_HOST=central
      - CENTRAL_PORT=5050
      - CP_ID=CP007
      - ENGINE_HOST=ev_cp_e_001
      - ENGINE_PORT=7000
      - REGISTRY_URL=https://registry:8080
      - REGISTRY_VERIFY_SSL=false
      - CP_LOCATION=Dock-1
    volumes:
      - ../ChargingPoints:/app
    command: ["sleep", "infinity"]

  driver:
    build:
      context: ..
      dockerfile: Deploy/Dockerfile.drivers
    hostname: driver_1
    container_name: driver_1
    depends_on:
      init-kafka: { condition: service_completed_successfully }
    environment:
      - KAFKA_BOOTSTRAP=broker:9092
    volumes:
      - ../Drivers:/app
    command: ["python","EV_Driver.py","broker:9092","DRIVER01"]
    stdin_open: true
    tty: true
  
  registry:
    build:
      context: ..
      dockerfile: Deploy/Dockerfile.registry
    hostname: registry
    container_name: registry
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_JWT_SECRET=dev_registry_secret
    volumes:
      - ../Registry:/app/Registry
    command: ["8080"]
  
  init-kafka:
    image: apache/kafka:latest
    container_name: init-kafka
    depends_on:
      broker: { condition: service_healthy }
    command: >
      bash -lc "
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --create --if-not-exists --topic requests --partitions 3 --replication-factor 1;
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --create --if-not-exists --topic telemetry --partitions 3 --replication-factor 1;
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --create --if-not-exists --topic commands --partitions 3 --replication-factor 1;
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --create --if-not-exists --topic tickets --partitions 3 --replication-factor 1;
        echo 'Kafka topics ready';
      "
    restart: "no"
